//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATRAVELOGGIA_MVC.WebAPI
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.Xml.Serialization;
    
    public partial class Map
    {
        public Map()
        {
            this.Sites = new HashSet<Site>();
        }
    
        public int MapID { get; set; }
        public string MapName { get; set; }
        public int MemberID { get; set; }
        public Nullable<decimal> MinX { get; set; }
        public Nullable<decimal> MaxX { get; set; }
        public Nullable<decimal> MinY { get; set; }
        public Nullable<decimal> MaxY { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> FromPhone { get; set; }
        public Nullable<System.DateTime> LastRevision { get; set; }
        public Nullable<bool> HasLayers { get; set; }

        [XmlIgnore]
        [IgnoreDataMember]
        public virtual ICollection<Site> Sites { get; set; }
    }
}
