//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATRAVELOGGIA_MVC.WebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class traveloggiaDBEntities : DbContext
    {
        public traveloggiaDBEntities()
            : base("name=traveloggiaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FBOneShotSite> FBOneShotSites { get; set; }
        public DbSet<FBSharedPhoto> FBSharedPhotos { get; set; }
        public DbSet<Journal> Journals { get; set; }
        public DbSet<Layer> Layers { get; set; }
        public DbSet<Map> Maps { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<Photo> Photos { get; set; }
        public DbSet<Rating> Ratings { get; set; }
        public DbSet<Site> Sites { get; set; }
        public DbSet<TraveloggiaEdition> TraveloggiaEditions { get; set; }
        public DbSet<Unhandled> Unhandleds { get; set; }
    }
}
